### PR TITLE
Modify devcontainer to use sinergym's DockerHub image

### PR DESCRIPTION
**Pull request by miguems**
## Description
.devcontainer is used by vscode to create a coding environment. Currently, we were using /Dockerfile for that environment. That image needed to be locally compiled everytime. Because we are already compiling that image and uploading it to Dockerhub, this PR proposes to use the DockerHub hosted image instead of locally creating it.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/jajimer/sinergym/blob/main/CONTRIBUTING.md) for new features and bug fixes)

Why is this change required? What problem does it solve? Please, reference issue or issues opened previously.

Fixes #(issue or issues)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Others

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/jajimer/sinergym/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests.
- [ ] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `autopep8` second level aggressive.
- [ ] I have reformatted the code using `isort`.
- [ ] I have ensured `cd docs && make spelling && make html` pass (**required** if documentation has been updated.)
- [ ] I have ensured `pytest tests/ -vv` pass. (**required**).
- [ ] I have ensured `pytype -d import-error sinergym/` pass. (**required**)

## Changelog:

- Modify .devcontainer.
- Updated version to 1.8.1.

### CODE REVIEW

**Comment by AlejandroCN7** [comment]
Hi @miguems ! Have you tried using Visual Studio Code with this new devcontainer? Does it work?

**Comment by miguems** [comment]
Yes. @jajimer and I tested it yesterday evening independently, and works. An additional advantage of this is that vscode does not need to perform a `docker build` in M1 macs (though you end up using a docker image compiled for another architecture). 

The only thing that we are not sure is whether or not using a explicit tag (e.g. `FROM alejandrocn7/sinergym:dev`) or always use the latest pushed image.

**Comment by miguems** [comment]
@AlejandroCN7, as you have a linux machine, please try in your machine if this new devcontainer works there.

**Comment by AlejandroCN7** [comment]
I have tried in my Linux machine, and it seems to work correctly:

Captura de pantalla de 2022-03-28 16-35-17

In that capture, it uses `.../sinergym/.devcontainer/Dockerfile` instead of `.../sinergym/Dockerfile`, so your changes have taken effect, and it hasn't given me any problems apparently :)

**Pull request merged**
