### PR TITLE
Corrects bug with normalisation ranges in battery

### PR DESCRIPTION
**Pull request by biemann**
Aims to correct minor bugs with normalisation in the DRL battery

Wrong keyword extracted from environment name
Normalisation ranges inconsistent with the extracted keyword from environment
Normalisation ranges not passed to gym environment in DRL usage (correct in DRL battery)
(minor: change variable name from range to norm_range, as I suppose it was introduced for this purpose before)

### CODE REVIEW

**Comment by biemann** [comment]
Sorry, it seems that I messed up my pull request. I meant only to submit the first commit. I am trying to correct this.

**Comment by AlejandroCN7** [comment]
It seems that we are experiencing issues with Github Actions on pull requests coming from forked repositories, it is the first :). We will try to solve it as soon as possible.

**Comment by biemann** [comment]
No problem :)

**Comment by AlejandroCN7** [comment]
Hello @biemann, we fixed this issue and your pull request should be pass without problems in the automated tests. Please, do the next:

- Update your forked main branch with ours.
- Apply your changes again.
- Create a new pull request to our main branch.

Thank you so much for your interest and sorry for the inconvenience caused.

**Pull request merged**
